# 1. Motor de base de datos
quarkus.datasource.db-kind=postgresql

# 2. Credenciales Docker Compose
quarkus.datasource.username=postgres
quarkus.datasource.password=admin

# 3. URL de conexión Reactiva al puerto expuesto por Docker
quarkus.datasource.reactive.url=postgresql://localhost:5432/microhumans

# 4. Estrategia de Hibernate (Crea o actualiza las tablas automáticamente al arrancar)
quarkus.hibernate-orm.database.generation=update

# 5. Opcional: Muestra el SQL en la consola (Súper útil para debuggear en desarrollo)
quarkus.hibernate-orm.log.sql=true