quarkus.datasource.db-kind=postgresql

# Usa variables de entorno, pero si no existen (como en tu local), toma postgres/admin
quarkus.datasource.username=${DB_USER:postgres}
quarkus.datasource.password=${DB_PASSWORD:admin}

# Separamos la URL local de la de producción
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5432/microhumans
%prod.quarkus.datasource.reactive.url=${DB_URL}

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true